### PR TITLE
postgres: Remove `diesel` (fixes #148)

### LINKED ISSUE #148: postgres 12 + postgis: find_srid(information_schema.sql_identifier, [...]) does not exist
repro steps:

1. `docker run --name some-postgis -e POSTGRES_PASSWORD=mysecretpassword -d postgis/postgis` (it goes into background)
2. `docker run -it --link some-postgis:postgres --rm postgres bash`
3. `psql "postgres://postgres:mysecretpassword@$POSTGRES_PORT_5432_TCP_ADDR/postgres"`
3. `create table seamus_test (id text, the_geom geometry(Geometry, 3857))`
4. install wget, grab the latest dbcrossbar
4. `./dbcrossbar cp "postgres://postgres:mysecretpassword@$POSTGRES_PORT_5432_TCP_ADDR/postgres#seamus_test" csv:a.csv`

you will get:

```
root@52274a9d99f4:/# ./dbcrossbar cp "postgres://postgres:mysecretpassword@$POSTGRES_PORT_5432_TCP_ADDR/postgres#seamus_test" csv:a.csv
Error: error reading schema from postgres://postgres:XXXXXX@172.17.0.2/postgres#seamus_test
  caused by: function find_srid(information_schema.sql_identifier, information_schema.sql_identifier, information_schema.sql_identifier) does not exist
```

### PR DESCRIPTION
**Pull request by emk**
We have historically used two Postgres drivers:

- `tokio-postgres` because it's async and supports bulk COPY commands
  nicely.
- `diesel` for more complex queries, because it had type checking.

The `diesel` code mostly predates `dbcrossbar`. We inherited it from
`schemaconv`. But it has a number of issues:

1. It requires static libpq and OpenSSL.
2. It's synchronous.
3. It has subtle different URL connection parameters than
   `tokio-postgres`.
4. It will never support `rustls`, allowing us to drop OpenSSL
   everywhere.

Furthermore, diesel didn't protect us from a type-related behavior
change in PostgreSQL 12. So I've decided to remove `diesel` and write a
small amount of raw SQL.

Of course, this means we lose compile-time checking. But since we don't
control `information_schema.*` or `Find_SRID`, that type checking doen't
buy us much.

Technically this breaks the `dbcrossbarlib` API, but since we don't
commit to semvar for that API yet, I'm not going to bump the version
accordingly.

### CODE REVIEW

File: dbcrossbarlib/src/drivers/postgres_shared/catalog.rs [hunk 1]
```diff
@@ -73,32 +64,51 @@ impl PgColumnSchema {
...
+    let count_matching_tables_sql = r#"
+SELECT COUNT(*) AS count
+FROM information_schema.tables
+WHERE
+    table_schema = $1 AND
+    table_name = $2
+"#;
+    let row = client
+        .query_one(count_matching_tables_sql, &[&schema, &table])
+        .await?;
```
Comment (seamusabshere) [inline dbcrossbarlib/src/drivers/postgres_shared/catalog.rs:86]: very satisfying

at this point in my career i'm just... not very interested in sql generation

didn't you mention there was a rust postgres driver that would parse the sql you provide and get types from it?

Comment (emk) [reply dbcrossbarlib/src/drivers/postgres_shared/catalog.rs:86]: Yes, `sqlx`.

`diesel` is really an excellent example of what can be done with a sufficiently smart generator, and it works beautifully in something like `falconeri` where we control the tables & migrations. It ensures that the Rust code and our queries actually match the database, in detail. That's useful because `falconeri` doesn't have enough integration tests, bec

But here we only have like 3 tables, none of which we control, so it's not buying us anywhere _near_ enough to put up with two Postgres drivers. I have no plans to switch from `tokio-postgres` to `sqlx`, because we have plenty of experience doing giant `COPY` operations with `tokio-postgres`, and because `sqlx` wouldn't buy us much here for reasons similar to `diesel`. Besides, this code changes once a year or so. Getting strong types for just these three queries is not a priority.
